name: Zig CI
  
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  prepare:
    name: Install Extism Runtime
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/libextism
  zig:
    name: Zig CI
    runs-on: ${{ matrix.os }}
    needs: prepare
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        zig_version: ["master"] # eventually use multiple versions once stable
        rust:
          - stable
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Download libextism.so
        uses: actions/download-artifact@v2
        with:
          name: libextism-so-artifact
      - name: Download libextism.h
        uses: actions/download-artifact@v2
        with:
          name: libextism-h-artifact
      - name: Move the files because download can't sudo
        run: |
          ls -lah ./
          sudo mv libextism.so /usr/local/lib/
          sudo mv extism.h /usr/local/include/
      - name: Setup Zig env
        uses: goto-bus-stop/setup-zig@v2
        with: 
          version: ${{ matrix.zig_version }}

      - name: Test Zig Host SDK
        run: |
          zig version
          LD_LIBRARY_PATH=/usr/local/lib zig build test
